plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

// Tutaj wpisujesz wersję swojego moda, widoczną w grze i nazwie pliku:
version = '26.1.2'
group = 'com.modpack.roseprogression'

base {
    archivesName = 'rose_progression'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    // Tutaj silnik pobiera środowisko Minecrafta 1.21.1, na którym bazuje paczka:
    version = '21.1.108'

    mods {
        rose_progression {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}
