modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="rose_progression"
version="26.1.2"
displayName="Rose Progression Fix"
description="Wymusza poziom Rose do wydobywania rud diamentu z predkoscia 7.0."

[[dependencies.rose_progression]]
modId="neoforge"
type="required"
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.rose_progression]]
modId="progression_reborn"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
